service:
  name: managerTodos

plugins:
  - serverless-offline
  - serverless-webpack

custom: 
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
  dynamodb:
    stages:
      - dev
      - local
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  region: ${env:AWS_REGION}
  runtime: nodejs12.x
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "*"

functions:
  health:
    handler: src/functions/hello.handle
    events:
      - http:
          path: /hello
          method: GET
          cors: true

  createUser:
    handler: src/functions/createUser.handle
    events:
      - http:
          path: /users
          method: POST
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action: 
          - dynamodb:Query
          - dynamodb:PutItem

  createTodo: 
    handler: src/functions/createTodo.handle
    events:
      - http:
          path: /todos/{user_id}
          method: POST
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action: 
          - dynamodb:PutItem

  listTodos: 
    handler: src/functions/listTodos.handle
    events:
      - http:
          path: /todos/{user_id}
          method: GET
          cors: true
    iamRoleStatements:
      - Effect: Allow
        Action: 
          - dynamodb:Query
